version: "3.8"
services:
  app:
    image: e5vosdo-snimrod
    ports:
      - "3000:3000"
    secrets:
      - PUBLIC_VAPID_KEY
      - PRIVATE_VAPID_KEY
      - AUTH_SECRET
      - AUTH_TRUST_HOST
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - IGNORE_BUILD_ERRORS
      - FAKE_AUTH
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    environment:
      PUBLIC_VAPID_KEY: ${PUBLIC_VAPID_KEY}
      PRIVATE_VAPID_KEY: ${PRIVATE_VAPID_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      IGNORE_BUILD_ERRORS: ${IGNORE_BUILD_ERRORS}
      FAKE_AUTH: ${FAKE_AUTH}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

secrets:
  PUBLIC_VAPID_KEY:
    external: true
  PRIVATE_VAPID_KEY:
    external: true
  AUTH_SECRET:
    external: true
  AUTH_TRUST_HOST:
    external: true
  GOOGLE_CLIENT_ID:
    external: true
  GOOGLE_CLIENT_SECRET:
    external: true
  IGNORE_BUILD_ERRORS:
    external: true
  FAKE_AUTH:
    external: true
  MYSQL_HOST:
    external: true
  MYSQL_PORT:
    external: true
  MYSQL_DATABASE:
    external: true
  MYSQL_USER:
    external: true
  MYSQL_PASSWORD:
    external: true
