name: Monorepo CI

on:
  push:
    branches: ["*"]

concurrency:
  group: monorepo-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Lint (web)
    runs-on: ubuntu-latest

    env:
      # Shared secrets & runtime env
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_TRUST_HOST: ${{ secrets.AUTH_TRUST_HOST }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      SERVICE_ACCOUNT_KEY_PATH: ${{ secrets.SERVICE_ACCOUNT_KEY_PATH }}
      BACKUP_FOLDER_ID: ${{ secrets.BACKUP_FOLDER_ID }}
      IGNORE_BUILD_ERRORS: ${{ secrets.IGNORE_BUILD_ERRORS }}
      FAKE_AUTH: ${{ secrets.FAKE_AUTH }}

      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}

      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      PUBLIC_VAPID_KEY: ${{ secrets.PUBLIC_VAPID_KEY }}
      PRIVATE_VAPID_KEY: ${{ secrets.PRIVATE_VAPID_KEY }}

      # Turbo cache can leverage CI marker
      TURBO_FORCE: true
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for turbo's changed files detection

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            apps/web/package-lock.json

      - name: Restore Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-
            turbo-${{ runner.os }}-

      - name: Install dependencies (root workspaces)
        run: npm install

      - name: Lint (affected web)
        run: npx turbo run lint --filter=e5vosdo-web...

      - name: Build (affected web)
        run: npx turbo run build --filter=e5vosdo-web...

      - name: Save Turbo cache
        if: always()
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}

      - name: Summarize Build Output
        if: success()
        run: |
          echo "Web build completed." >> $GITHUB_STEP_SUMMARY
          echo "Commit: $GITHUB_SHA" >> $GITHUB_STEP_SUMMARY
