name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - "*--builddocker*"
  issue_comment:
    types: [created]

jobs:
  build:
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'issue_comment' &&
       contains(github.event.comment.body, 'run docker-build') &&
       github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/e5vosdo-snimrod:latest
          build-args: |
            AUTH_SECRET=${{ secrets.AUTH_SECRET }}
            AUTH_TRUST_HOST=${{ secrets.AUTH_TRUST_HOST }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            SERVICE_ACCOUNT_KEY=${{ secrets.SERVICE_ACCOUNT_KEY }}
            SERVICE_ACCOUNT_KEY_PATH=${{ secrets.SERVICE_ACCOUNT_KEY_PATH }}
            BACKUP_FOLDER_ID=${{ secrets.BACKUP_FOLDER_ID }}
            IGNORE_BUILD_ERRORS=${{ secrets.IGNORE_BUILD_ERRORS }}
            FAKE_AUTH=${{ secrets.FAKE_AUTH }}
            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            MYSQL_PORT=${{ secrets.MYSQL_PORT }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
            NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
            PUBLIC_VAPID_KEY=${{ secrets.PUBLIC_VAPID_KEY }}
            PRIVATE_VAPID_KEY=${{ secrets.PRIVATE_VAPID_KEY }}

      - name: Log out from GHCR
        run: docker logout ghcr.io
